In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
from pathlib import Path          

import ipywidgets as widgets
from IPython.display import display
from datetime import date, timedelta

import ptm_lib as ptm
%load_ext autoreload
%autoreload 2

In [2]:
base_dir = Path.cwd()
fig_dir = base_dir / "Figures"

# ETFs US

In [29]:
from_date = date(1928, 1, 1) 
today = date.today()
# ETFs Bonds
tickers = ['TLT','SHY','LQD','JNK','HYG']
file = 'ETFS'
frequency = 'd' 

data = ptm.loadNupdate(tickers, from_date, today, frequency, file)

# Plotting 
ptm.plot_select(data, tickers)
# Spread Analysis
ptm.spread_analysis(data, tickers, mode='log', fig_dir=None)

FRED download failed: FRED download returned invalid or empty data.

Falling back to yfinance...

[*********************100%***********************]  5 of 5 completed

5 Failed downloads:
['TLT', 'LQD', 'JNK', 'SHY', 'HYG']: YFPricesMissingError('possibly delisted; no price data found  (1d 2025-11-08 -> 2025-11-10)')

No new data

interactive(children=(Dropdown(description='Ticker:', options=('TLT', 'SHY', 'LQD', 'JNK', 'HYG'), value='TLT'…

  Ticker                      Description
0    TLT   iShares 20+ Year Treasury Bond
1    SHY   iShares 1-3 Year Treasury Bond
2    LQD  iShares iBoxx $ Investment Grad
3    JNK  State Street SPDR Bloomberg Hig
4    HYG  iShares iBoxx $ High Yield Corp

interactive(children=(Dropdown(description='Ticker 1', options=('TLT', 'SHY', 'LQD', 'JNK', 'HYG'), value='TLT…

# Corporate Index Yields US

In [27]:
from_date = date(1928, 1, 1) 
today = date.today()
# INDEXES
tickers = ['BAMLC0A1CAAAEY','BAMLC0A4CBBBEY','BAMLH0A3HYCEY','DGS10']
file = 'INDEXES'
frequency = 'd' 

data = ptm.loadNupdate(tickers, from_date, today, frequency, file)

ptm.plot_select(data, tickers)

ptm.spread_analysis(data, tickers, fig_dir=None)

FRED download failed: FRED download returned invalid or empty data.

Falling back to yfinance...

[*********************100%***********************]  4 of 4 completed

4 Failed downloads:
['DGS10', 'BAMLC0A1CAAAEY', 'BAMLH0A3HYCEY', 'BAMLC0A4CBBBEY']: YFTzMissingError('possibly delisted; no timezone found')

No new data

interactive(children=(Dropdown(description='Ticker:', options=('BAMLC0A1CAAAEY', 'BAMLC0A4CBBBEY', 'BAMLH0A3HY…

,Ticker,Description
0,BAMLC0A1CAAAEY,ICE BofA AAA US Corporate Index Effective Yield
1,BAMLC0A4CBBBEY,ICE BofA BBB US Corporate Index Effective Yield
2,BAMLH0A3HYCEY,ICE BofA CCC & Lower US High Yield Index Effective Yield
3,DGS10,"Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis"

interactive(children=(Dropdown(description='Ticker 1', options=('BAMLC0A1CAAAEY', 'BAMLC0A4CBBBEY', 'BAMLH0A3H…